---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      container_name: ubuntudockercont
      image: ubuntudocker:latest
      platform: ubuntu
#  - name: centos-7.1

suites:
  - name: default 
    run_list: 
     - recipe[helloworld::default] 
