---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: centos-6-7 

suites:
  - name: default
    run_list:
    - recipe[java]
    - recipe[nginx]
    - recipe[mysql]
    - recipe[tomcat]
    attributes:
